import { Hono } from "hono";
import * as oauth from "../controllers/oauth";
import * as account from "../controllers/account";
import * as mcp from "../controllers/mcp";
import * as cloudstorage from "../controllers/cloudstorage";
import * as storefront from "../controllers/storefront";
import * as timeline from "../controllers/timeline";
import * as events from "../controllers/events";
import * as friends from "../controllers/friends";
import * as matchmaking from "../controllers/matchmaking";
import * as party from "../controllers/party";
import * as data from "../controllers/data";
import * as eula from "../controllers/eula";
import * as update from "../controllers/update";
import * as other from "../controllers/other";
import * as arc from "../controllers/arc";
import * as launcher from "../controllers/launcher";
import * as shop from "../controllers/shop";
import { authMiddleware } from "../middleware/auth";

const app = new Hono();

app.post("/account/api/oauth/token", oauth.oauthToken);
app.get("/account/api/oauth/verify", oauth.verifyToken);
app.delete("/account/api/oauth/sessions/kill", oauth.deleteTokenHandler);
app.delete("/account/api/oauth/sessions/kill/:token", oauth.deleteTokenHandler);
app.post("/account/api/oauth/deviceAuthorization", authMiddleware, oauth.createDeviceAuthHandler);
app.delete("/account/api/deviceAuthorization/:deviceAuthId", authMiddleware, oauth.deleteDeviceAuthHandler);
app.get("/account/api/oauth/exchange", authMiddleware, oauth.createExchangeCode);
app.get("/login", oauth.login);
app.post("/login", oauth.login);
//app.post("/register", oauth.register);
app.post("/account/api/public/account/create", oauth.register);
//app.get("/redirect", oauth.redirect);

app.get("/account/api/public/account/:accountId", authMiddleware, account.accountDetails);
app.get("/account/api/public/account", authMiddleware, account.queryFetch);
app.get("/account/api/public/account/displayName/:displayName", account.displayNameFetch);
app.get("/account/api/public/account/:accountId/externalAuths", authMiddleware, other.emptyArray);
app.get("/persona/api/public/account/lookup", authMiddleware, account.searchUsers);
app.get("/api/v1/search/:accountId", authMiddleware, account.searchUsers);
app.get("/sdk/v1/identity/accounts", authMiddleware, account.sdkAccounts);
app.get("/sdk/v1/identities", authMiddleware, account.sdkAccounts);
app.get("/statsproxy/api/statsv2/account/:accountId", authMiddleware, account.statsProxy);
app.get("/account/api/epicdomains/ssodomains", other.emptyArray);
app.get("/content-controls/:accountId/settings", account.getContentControls);
app.post("/content-controls/:accountId/verify-pin", account.contentControlsPin);
app.get("/fortnite/api/game/v2/privacy/account/:accountId", authMiddleware, account.privacy);
app.post("/fortnite/api/game/v2/privacy/account/:accountId", authMiddleware, account.privacy);
app.get("/fortnite/api/game/v2/br-inventory/account/:accountId", authMiddleware, account.brInventory);
app.get("/fortnite/api/socialban/v1/:accountId", account.socialBan);

app.post("/fortnite/api/game/v2/profile/:accountId/client/:operation", authMiddleware, mcp.mcpPost);
app.post("/fortnite/api/game/v2/profile/:accountId/dedicated_server/:operation", mcp.mcpPost);
app.post("/fortnite/api/game/v3/profile/:accountId/client/:operation", authMiddleware, mcp.mcpPost);

app.get("/fortnite/api/cloudstorage/system", authMiddleware, cloudstorage.listSystemFiles);
app.get("/fortnite/api/cloudstorage/system/:file", authMiddleware, cloudstorage.serveSystemFile);
app.get("/fortnite/api/cloudstorage/user/:accountId", authMiddleware, cloudstorage.listUserFiles);
app.get("/fortnite/api/cloudstorage/user/:accountId/:file", authMiddleware, cloudstorage.serveUserFile);
app.put("/fortnite/api/cloudstorage/user/:accountId/:file", authMiddleware, cloudstorage.uploadUserFile);

app.get("/fortnite/api/storefront/v2/keychain", storefront.getKeychainHandler);
app.get("/fortnite/api/storefront/v2/catalog", storefront.getCatalog);
app.get("/catalog/api/shared/bulk/offers", storefront.getBulkCatalog);
app.get("/fortnite/api/storefront/v2/gift/check_eligibility/recipient/:recipientId/offer/:offerId", authMiddleware, storefront.giftCheckEligibility);

app.get("/fortnite/api/calendar/v1/timeline", timeline.getTimeline);
app.get("/api/v1/events/Fortnite/download/:accountId", authMiddleware, events.getArenaEvents);
app.post("/api/v1/events/Fortnite/:eventId/history/:accountId", authMiddleware, events.postEventHistory);

app.post("/fortnite/api/game/v2/events/Fortnite/:eventId/history/:accountId", authMiddleware, events.postEventHistory);
app.get("/fortnite/api/game/v2/events/tournamentandhistory/:accountId/:windowId", authMiddleware, events.getEvents);
app.get("/api/v1/events/Fortnite/:accountId", authMiddleware, events.getArenaEvents);
app.get("/api/v1/games/fortnite/tracks/public", events.getEventTokens);
app.get("/api/v1/leaderboards/Fortnite/:accountId", authMiddleware, events.getLeaderboards);
app.post("/fortnite/api/game/v2/profile/:accountId/client/DownloadSubgameForEpicLauncher", events.downloadSubgame);

app.get("/friends/api/v1/:accountId/summary", authMiddleware, friends.getFriendsSummary);
app.get("/friends/api/public/friends/:accountId", authMiddleware, friends.getFriends);
app.get("/friends/api/public/blocklist/:accountId", authMiddleware, friends.getBlocklist);
app.get("/friends/api/v1/:accountId/blocklist", authMiddleware, friends.getBlocklist);
app.post("/friends/api/v1/:accountId/friends/:friendId", authMiddleware, friends.addFriend);
app.delete("/friends/api/v1/:accountId/friends/:friendId", authMiddleware, friends.removeFriend);
app.post("/friends/api/v1/:accountId/blocklist/:friendId", authMiddleware, friends.blockFriend);
app.delete("/friends/api/v1/:accountId/blocklist/:friendId", authMiddleware, friends.unblockFriend);
app.get("/friends/api/public/list/fortnite/:accountId/recentPlayers", authMiddleware, friends.friendsRecent);
app.get("/friends/api/v1/:accountId/settings", authMiddleware, friends.friendsSettings);
app.get("/friends/api/v1/:accountId/friends/:friendId/alias", authMiddleware, friends.getFriendAlias);
app.put("/friends/api/v1/:accountId/friends/:friendId/alias", authMiddleware, friends.setFriendAlias);
app.delete("/friends/api/v1/:accountId/friends/:friendId/alias", authMiddleware, friends.deleteFriendAlias);
app.post("/friends/api/public/friends/:accountId/:friendId", authMiddleware, friends.addFriend);
app.delete("/friends/api/public/friends/:accountId/:friendId", authMiddleware, friends.removeFriend);
app.post("/friends/api/v1/:accountId/incoming/:friendId/accept", authMiddleware, friends.addFriend);

app.post("/fortnite/api/matchmaking/session/:accountId", authMiddleware, matchmaking.createMatchmakingTicket);
app.get("/fortnite/api/matchmaking/session/:accountId/:ticketId", authMiddleware, matchmaking.getMatchmakingTicket);
app.delete("/fortnite/api/matchmaking/session/:accountId/:ticketId", authMiddleware, matchmaking.deleteMatchmakingTicket);
app.get("/fortnite/api/matchmaking/session/:sessionId", matchmaking.getMatchmakingSession);
app.post("/fortnite/api/matchmaking/session/:sessionId/join", matchmaking.joinSession);
app.post("/fortnite/api/matchmaking/session/:sessionId/join/:accountId", matchmaking.joinSession);
app.delete("/fortnite/api/matchmaking/session/:sessionId/join/:accountId", matchmaking.leaveSession);
app.put("/fortnite/api/matchmaking/session/:sessionId", matchmaking.updateSession);
app.get("/fortnite/api/game/v2/matchmaking/account/:accountId/session/:sessionId", authMiddleware, matchmaking.getMatchmakingSession);
app.get("/fortnite/api/game/v2/matchmakingservice/ticket/player/:accountId", authMiddleware, matchmaking.createMatchmakingTicket);
app.get("/fortnite/api/matchmaking/session/findPlayer/*", matchmaking.findSessions);
app.post("/fortnite/api/matchmakingservice/session/findSession", matchmaking.findSessions);
app.post("/fortnite/api/matchmaking/session/matchMakingRequest", matchmaking.findSessions);
app.get("/fortnite/api/statsv2/wait_times", matchmaking.getWaitTimes);

app.get("/party/api/v1/Fortnite/user/:accountId", authMiddleware, party.getUserParties);
app.get("/party/api/v1/Fortnite/user/:accountId/notifications/undelivered/count", authMiddleware, party.partyUndeliveredCount);
app.post("/party/api/v1/Fortnite/parties", authMiddleware, party.createParty);
app.get("/party/api/v1/Fortnite/parties/:partyId", party.getParty);
app.patch("/party/api/v1/Fortnite/parties/:partyId", authMiddleware, party.updateParty);
app.delete("/party/api/v1/Fortnite/parties/:partyId", authMiddleware, party.deleteParty);
app.post("/party/api/v1/Fortnite/parties/:partyId/members/:accountId/join", authMiddleware, party.joinParty);
app.delete("/party/api/v1/Fortnite/parties/:partyId/members/:accountId", authMiddleware, party.leaveParty);
app.post("/party/api/v1/Fortnite/parties/:partyId/members/:accountId/kick", authMiddleware, party.kickMember);
app.patch("/party/api/v1/Fortnite/parties/:partyId/members/:accountId/meta", authMiddleware, party.updateMember);
app.post("/party/api/v1/Fortnite/parties/:partyId/members/:accountId/promote", authMiddleware, party.promoteMember);
app.post("/party/api/v1/Fortnite/parties/:partyId/invites/:accountId", authMiddleware, party.sendInvite);
app.delete("/party/api/v1/Fortnite/parties/:partyId/invites/:accountId/decline", authMiddleware, party.declineInvite);
app.post("/party/api/v1/Fortnite/parties/:partyId/invites/:accountId/:someId/decline", authMiddleware, party.declineInvite);
app.get("/party/api/v1/Fortnite/user/:accountId/pings", authMiddleware, party.getPings);
app.post("/party/api/v1/Fortnite/user/:accountId/pings/:pingerId", authMiddleware, party.sendPing);
app.delete("/party/api/v1/Fortnite/user/:accountId/pings/:pingerId", authMiddleware, party.deletePing);
app.get("/party/api/v1/Fortnite/user/:accountId/pings/:pingerId/parties", authMiddleware, party.getPartiesForPing);
app.post("/party/api/v1/Fortnite/user/:accountId/pings/:pingerId/join", authMiddleware, party.joinPingParty);
app.post("/party/api/v1/Fortnite/members/:accountId/intentions/:senderId", authMiddleware, party.createIntention);
app.post("/party/api/v1/Fortnite/parties/lookup", authMiddleware, party.getPartyLookup);
app.get("/party/api/v1/Fortnite/parties/:partyId/members/:accountId/meta", party.memberMeta);

app.get("/content/api/pages/fortnite-game", data.getContentPages);
app.get("/fortnite/api/game/v2/world/info", other.emptyObject);
app.get("/socialban/api/public/v1/:accountId", account.socialBan);
app.post("/datarouter/api/v1/public/data", other.okResponse);
app.get("/lightswitch/api/service/bulk/status", data.getLightswitchBulk);
app.get("/lightswitch/api/service/Fortnite/status", data.getLightswitch);
app.get("/fortnite/api/game/v2/enabled_features", data.getEnabledFeatures);
app.get("/fortnite/api/receipts/v1/account/:accountId/receipts", data.getReceipts);
app.get("/entitlement/api/account/:accountId/entitlements", data.getEntitlements);
app.get("/fortnite/api/game/v2/creative/discovery/surface/:accountId", data.getDiscovery);
app.get("/links/api/fn/mnemonic/:playlistId", data.getMnemonic);
app.post("/links/api/fn/mnemonic", data.getMnemonic);
app.get("/fortnite/api/game/v2/creative/discovery/surface/CreativeDiscoverySurface_Frontend/:accountId", data.getDiscovery);
app.get("/api/v1/discovery/surface/:surfaceId/page", data.getActivePanels);
app.get("/launcher/api/public/distributionpoints", data.getDistributionPoints);
app.get("/launcher/api/public/distributionpoints/", data.getDistributionPoints);
app.get("/content/api/pages/*", data.getContentPages);
app.get("/fortnite/api/v2/versioncheck/*", update.checkVersion);
app.get("/fortnite/api/versioncheck/*", update.checkVersion);
app.get("/waitingroom/api/waitingroom", update.waitingRoom);

app.get("/eulatracking/api/public/agreements/fn/account/:accountId", eula.checkEulaAccepted);
app.post("/eulatracking/api/public/agreements/fn/version/:version/account/:accountId/accept", eula.acceptEula);
app.get("/eulatracking/api/shared/agreements/fn", eula.getEula);

app.get("/fortnite/api/game/v2/world/info", other.emptyObject);
app.get("/region", other.getRegion);
app.get("/v1/epic-settings/public/users/:accountId/values", other.getAccountSettings);
app.get("/fortnite/api/game/v2/twitch/:accountId", other.emptyObject);
app.post("/fortnite/api/game/v2/twitch/:accountId", other.okResponse);
app.get("/fortnite/api/storeaccess/v1/request_access/:accountId", data.grantAccess);
app.get("/socialban/api/public/v1/:accountId", account.socialBan);
app.get("/api/v1/user/setting", other.getSocialSettings);
app.post("/api/v1/user/setting", other.setSocialSettings);
app.post("/tracking/api/v1/tracking/status", other.trackingStatus);
app.post("/fortnite/api/game/v2/tryPlayOnPlatform/account/:accountId", other.getTryPlayOnPlatform);
app.get("/fortnite/api/version", other.getVersion);
app.get("/fortnite/api/v2/versioncheck/:platform", update.checkVersion);
app.get("/affiliate/api/public/affiliates/slug/:code", other.getAffiliate);
app.get("/affiliate/api/public/affiliates/search", other.getAffiliateSearch);
app.post("/affiliate/api/public/affiliates/slug/:code", other.setAffiliate);

app.post("/outgoing/v1/anticheat/private/ban", arc.arcBan);
app.post("/outgoing/v1/anticheat/private/revoke", arc.arcRevoke);

//app.post("/api/exlo/vbucks/kill", launcher.vbucksOnKill);
//app.post("/api/exlo/vbucks/win", launcher.vbucksOnWin);
app.post("/api/exlo/vbucks/add", launcher.addVbucks);
app.post("/api/exlo/hype/add", launcher.addHype);
//app.post("/api/exlo/hype/kill", launcher.hypeOnKill);
//app.post("/api/exlo/hype/placement", launcher.hypeOnPlacement);
app.get("/api/exlo/vbucks/:name", launcher.getVbucks);
app.get("/api/exlo/leaderboard/hype", launcher.getHypeLeaderboardHandler);
app.get("/api/exlo/hype/:name", launcher.getHype);
app.get("/api/exlo/auth/discord", launcher.discordAuth);
app.get("/api/exlo/auth/discord/", launcher.discordAuth);
app.get("/api/exlo/auth/discord/callback", launcher.discordCallback);
app.get("/api/exlo/auth/discord/callback/", launcher.discordCallback);
app.post("/api/exlo/shop/rotate", shop.rotateShopHandler);
app.get("/api/exlo/shop/data", shop.getShopData);
app.get("/api/user/:username", launcher.GetUser);

app.get("/health", other.healthCheck);
app.all("*", other.notFound);

export default app;
