[/Script/FortniteGame.FortRuntimeOptions]
!DisabledFrontendNavigationTabs=ClearArray
+DisabledFrontendNavigationTabs=(TabName="AthenaStore",TabState=EFortRuntimeOptionTabState::Hidden)
+DisabledFrontendNavigationTabs=(TabName="AthenaChallenges",TabState=EFortRuntimeOptionTabState::Hidden)
;+DisabledFrontendNavigationTabs=(TabName="AthenaCareer",TabState=EFortRuntimeOptionTabState::Hidden)
+DisabledFrontendNavigationTabs=(TabName="AthenaCompete",TabState=EFortRuntimeOptionTabState::Hidden)
;+DisabledFrontendNavigationTabs=(TabName="Showdown",TabState=EFortRuntimeOptionTabState::Hidden)
bEnableGlobalChat=true
bDisableGifting=false
bDisableGiftingPC=false
bDisableGiftingPS4=false
bDisableGiftingXB=false
bSkipTrailerMovie=true
bAlwaysPlayTrailerMovie=false
bSkipInternetCheck=true
bLoginXBLDisabled=true
bLoginPSNDisabled=true
bHidePlusOnVbucksButton=true
bAlwaysForceTournamentLobbyPanelRefresh=true
bEnableEventScoreClamping=true
bEnableStartingPointCount=false
bEnableClientSettingsSaveToDisk=true
bEnableClientSettingsSaveToCloud=true
bShouldAthenaQueryRecentPlayers=false
ShowdownTournamentCacheExpirationHours=1
TournamentRefreshPlayerMaxRateSeconds=1
TournamentRefreshEventsMaxRateSeconds=1
TournamentRefreshPayoutMaxRateSeconds=1
+DisabledTabsForOutOfSeason=(TabName="BattlePass",TabState=Disabled)
+ExperimentalCohortPercent=(CohortPercent=100,ExperimentNum=20)
DaysOfFriendshipBeforeCanGift=0